services:
  v2raya:
    image: mzz2017/v2raya:latest
    container_name: v2raya
    restart: always
    privileged: true
    network_mode: host
    environment:
      - IPTABLES_MODE=legacy
      - V2RAYA_NFTABLES_SUPPORT=off
      - V2RAYA_LOG_FILE=/tmp/v2raya.log
    volumes:
      - /lib/modules:/lib/modules:ro
      - /etc/resolv.conf:/etc/resolv.conf
      - /etc/v2raya:/etc/v2raya