services:
  v2raya:
    image: mzz2017/v2raya:latest
    container_name: v2raya
    restart: always
    network_mode: host
    privileged: true
    environment:
      - IPTABLES_MODE=legacy
      - V2RAYA_NFTABLES_SUPPORT=off
    volumes:
      - /etc/v2raya:/etc/v2raya
      - /lib/modules:/lib/modules:ro
      - /etc/resolv.conf:/etc/resolv.conf